name: namer_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^3.0.1
  url_launcher: ^6.1.11
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  confetti: ^0.7.0
  flutter_staggered_animations: ^1.0.0
  widget_circular_animator: 1.0.0
  animated_text_kit: ^4.2.2
  chat_bubbles: ^1.6.0
  flutter_lints: ^2.0.0
  english_words: ^4.0.0
  provider: ^6.0.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image1.jpg
    - assets/image2.jpg
    - assets/image3.jpg
    - assets/image4.jpg
    - assets/alum_can.png
    - assets/band_aids.png
    - assets/burger.png
    - assets/cardboard_box.png
    - assets/charging_cable.png
    - assets/disposable_cup.png
    - assets/egg_shells.png
    - assets/food_leftover.png
    - assets/fruit_scraps.png
    - assets/game_console.png
    - assets/keyboard.png
    - assets/mask.png
    - assets/mouse.png
    - assets/newspaper.png
    - assets/pastic_bottle.png
    - assets/phone.png
    - assets/sanitary_napkins.png
    - assets/tampons.png
    - assets/tea_bags.png
    - assets/mom_congrats.jpeg
    - assets/mom_congrats.png
    - assets/Zephyr.png
    - assets/collectible_card_1.png
    - assets/collectible_card_2.png
    - assets/collectible_card_3.png
    - assets/collectible_card_0.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
